# Generated by Django 5.2.3 on 2025-07-13 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='minutes',
        ),
        migrations.AddField(
            model_name='schedule',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.IntegerField(default=0),
        ),
    ]
